// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bin/delete_proj": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回收站"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "description": "项目ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.DeleteProjQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.DeleteProjA"
                        }
                    }
                }
            }
        },
        "/file/create_document": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "创建文档",
                "parameters": [
                    {
                        "description": "文档名称，文档所属项目ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.CreateDocumentQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CreateDocumentA"
                        }
                    }
                }
            }
        },
        "/file/create_prototype": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "创建设计原型",
                "parameters": [
                    {
                        "description": "设计原型名称，设计原型所属项目ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.CreatePrototypeQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CreatePrototypeA"
                        }
                    }
                }
            }
        },
        "/file/create_uml": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "创建 Uml",
                "parameters": [
                    {
                        "description": "Uml名称，Uml所属项目ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.CreateUmlQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CreateUmlA"
                        }
                    }
                }
            }
        },
        "/file/enter_document": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "进入文档",
                "parameters": [
                    {
                        "description": "文档ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.EnterDocumentQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.EnterDocumentA"
                        }
                    }
                }
            }
        },
        "/file/get_files_by_name": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "搜索框",
                "parameters": [
                    {
                        "description": "文件名称（不一定是全名，子串搜索，为空时返回数据库中全部不在回收站的文件，包括设计原型、Uml、文档）",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetFilesByNameQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetFilesByNameA"
                        }
                    }
                }
            }
        },
        "/file/get_proj_by_id": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "获取项目信息",
                "parameters": [
                    {
                        "description": "项目ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetProjByIDQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetProjByIDA"
                        }
                    }
                }
            }
        },
        "/file/get_proj_documents": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "获取项目的文档",
                "parameters": [
                    {
                        "description": "项目ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetProjDocumentsQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetProjDocumentsA"
                        }
                    }
                }
            }
        },
        "/file/get_proj_prototypes": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "获取项目的设计原型",
                "parameters": [
                    {
                        "description": "项目ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetProjPrototypesQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetProjPrototypesA"
                        }
                    }
                }
            }
        },
        "/file/get_proj_umls": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "获取项目的 Uml 图",
                "parameters": [
                    {
                        "description": "项目ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetProjUmlsQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetProjUmlsA"
                        }
                    }
                }
            }
        },
        "/file/move_document_to_bin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "文档移入回收站",
                "parameters": [
                    {
                        "description": "文档 ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.MoveDocumentToBinQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MoveDocumentToBinA"
                        }
                    }
                }
            }
        },
        "/file/move_prototype_to_bin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "设计原型移入回收站",
                "parameters": [
                    {
                        "description": "设计原型ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.MovePrototypeToBinQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MovePrototypeToBinA"
                        }
                    }
                }
            }
        },
        "/file/move_uml_to_bin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "Uml 移入回收站",
                "parameters": [
                    {
                        "description": "Uml ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.MoveUmlToBinQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MoveUmlToBinA"
                        }
                    }
                }
            }
        },
        "/file/quit_document": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "退出文档",
                "parameters": [
                    {
                        "description": "文档ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.QuitDocumentQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.QuitDocumentA"
                        }
                    }
                }
            }
        },
        "/file/update_document": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "修改文档名称",
                "parameters": [
                    {
                        "description": "文档ID，文档的新名字（必填，可以填原名，不能和其他项目同名）",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.UpdateDocumentQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UpdateDocumentA"
                        }
                    }
                }
            }
        },
        "/file/update_prototype": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "修改设计原型名称",
                "parameters": [
                    {
                        "description": "设计原型ID，设计原型的新名字（必填，可以填原名，不能和其他项目同名）",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.UpdatePrototypeQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UpdatePrototypeA"
                        }
                    }
                }
            }
        },
        "/file/update_uml": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "修改 Uml 名称",
                "parameters": [
                    {
                        "description": "Uml ID，Uml的新名字（必填，可以填原名，不能和其他项目同名）",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.UpdateUmlQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UpdateUmlA"
                        }
                    }
                }
            }
        },
        "/file/upload_document": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第二页"
                ],
                "summary": "上传文档",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文档",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文档ID",
                        "name": "document_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UploadDocumentA"
                        }
                    }
                }
            }
        },
        "/group/add_member": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "parameters": [
                    {
                        "description": "用户id，团队id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.AddMemberQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AddMemberA"
                        }
                    }
                }
            }
        },
        "/group/create_group": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "parameters": [
                    {
                        "description": "团队名称，团队介绍",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.CreateGroupQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CreateGroupA"
                        }
                    }
                }
            }
        },
        "/group/get_group_members": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "parameters": [
                    {
                        "description": "团队id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetMembersQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetMembersA"
                        }
                    }
                }
            }
        },
        "/group/get_groups": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetGroupsA"
                        }
                    }
                }
            }
        },
        "/group/get_identity": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "parameters": [
                    {
                        "description": "团队id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetIdentityQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetIdentityA"
                        }
                    }
                }
            }
        },
        "/group/modify_group": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "parameters": [
                    {
                        "description": "团队id，团队名称，团队介绍",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.ModifyGroupQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ModifyGroupA"
                        }
                    }
                }
            }
        },
        "/group/remove_member": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "parameters": [
                    {
                        "description": "用户id，团队id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.RemoveMemberQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RemoveMemberA"
                        }
                    }
                }
            }
        },
        "/group/set_member_status": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "parameters": [
                    {
                        "description": "用户id，团队id，状态",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.SetMemberStatusQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SetMemberStatusA"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基本模块"
                ],
                "parameters": [
                    {
                        "description": "用户名，密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.LoginQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.LoginA"
                        }
                    }
                }
            }
        },
        "/ppage/create_ppage": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设计原型的页面"
                ],
                "summary": "创建设计原型的一个页面",
                "parameters": [
                    {
                        "description": "页面名称，页面数据（可选），页面所属设计原型ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.CreatePPageQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CreatePPageA"
                        }
                    }
                }
            }
        },
        "/ppage/delete_ppage": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设计原型的页面"
                ],
                "summary": "删除设计原型的某个页面",
                "parameters": [
                    {
                        "description": "页面ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.DeletePPageQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.DeletePPageA"
                        }
                    }
                }
            }
        },
        "/ppage/get_ppage_by_id": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设计原型的页面"
                ],
                "summary": "获取设计原型的某个页面",
                "parameters": [
                    {
                        "description": "页面ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetPPageByIDQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetPPageByIDA"
                        }
                    }
                }
            }
        },
        "/ppage/get_ppages": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设计原型的页面"
                ],
                "summary": "获取某个设计原型的所有页面的ID",
                "parameters": [
                    {
                        "description": "设计原型ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetPPagesQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetPPagesA"
                        }
                    }
                }
            }
        },
        "/ppage/update_ppage": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设计原型的页面"
                ],
                "summary": "修改设计原型的某个页面的名称或数据",
                "parameters": [
                    {
                        "description": "页面ID，页面名称（可选，如果没填或者为空字符串，则不修改），页面数据（可选，如果没填或者为空字符串，则不修改）",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.UpdatePPageQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UpdatePPageA"
                        }
                    }
                }
            }
        },
        "/proj/create_proj": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第一页"
                ],
                "summary": "创建项目",
                "parameters": [
                    {
                        "description": "项目名称，项目详情（可选），所属团队ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.CreateProjQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CreateProjA"
                        }
                    }
                }
            }
        },
        "/proj/get_proj_all": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第一页"
                ],
                "summary": "全部项目",
                "parameters": [
                    {
                        "description": "无",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetProjAllQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetProjAllA"
                        }
                    }
                }
            }
        },
        "/proj/get_proj_by_name": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第一页"
                ],
                "summary": "搜索框",
                "parameters": [
                    {
                        "description": "项目名称（不一定是全名，子串搜索，为空时返回数据库中全部不在回收站的项目）",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetProjByNameQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetProjByNameA"
                        }
                    }
                }
            }
        },
        "/proj/get_proj_create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第一页"
                ],
                "summary": "我创建的",
                "parameters": [
                    {
                        "description": "无",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetProjCreateQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetProjCreateA"
                        }
                    }
                }
            }
        },
        "/proj/get_proj_join": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第一页"
                ],
                "summary": "我参与的",
                "parameters": [
                    {
                        "description": "无",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetProjJoinQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetProjJoinA"
                        }
                    }
                }
            }
        },
        "/proj/move_proj_to_bin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第一页"
                ],
                "summary": "移入或移出回收站",
                "parameters": [
                    {
                        "description": "项目ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.MoveProjBinQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MoveProjBinA"
                        }
                    }
                }
            }
        },
        "/proj/update_proj": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目管理的第一页"
                ],
                "summary": "修改项目名称、项目描述",
                "parameters": [
                    {
                        "description": "项目ID，项目名称（必填，可以填原名，不能和其他项目同名），项目详情（可选）",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.UpdateProjQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UpdateProjA"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基本模块"
                ],
                "parameters": [
                    {
                        "description": "用户名，密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.RegisterQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RegisterA"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "parameters": [
                    {
                        "description": "用户名，密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.GetUserInfoQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetUserInfoA"
                        }
                    }
                }
            }
        },
        "/user/modify_info": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.ModifyInfoQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ModifyInfoA"
                        }
                    }
                }
            }
        },
        "/user/modify_password": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "parameters": [
                    {
                        "description": "新密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.ModifyPasswordQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ModifyPasswordA"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.Document": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "document_id": {
                    "type": "integer"
                },
                "document_name": {
                    "type": "string"
                },
                "document_url": {
                    "type": "string"
                },
                "proj_id": {
                    "type": "integer"
                },
                "status": {
                    "description": "1 正常、2 回收站",
                    "type": "integer"
                }
            }
        },
        "database.Group": {
            "type": "object",
            "properties": {
                "groupID": {
                    "type": "integer"
                },
                "groupInfo": {
                    "type": "string"
                },
                "groupName": {
                    "type": "string"
                },
                "userID": {
                    "description": "团队创建者",
                    "type": "integer"
                }
            }
        },
        "database.GroupMember": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "realName": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "database.PPage": {
            "type": "object",
            "properties": {
                "ppage_data": {
                    "type": "string"
                },
                "ppage_id": {
                    "type": "integer"
                },
                "ppage_name": {
                    "type": "string"
                },
                "ppage_url": {
                    "description": "先写上",
                    "type": "string"
                },
                "prototype_id": {
                    "type": "integer"
                }
            }
        },
        "database.PPageID": {
            "type": "object",
            "properties": {
                "ppage_id": {
                    "type": "integer"
                },
                "ppage_name": {
                    "type": "string"
                }
            }
        },
        "database.Proj": {
            "type": "object",
            "properties": {
                "group_id": {
                    "description": "项目所属团队",
                    "type": "integer"
                },
                "proj_id": {
                    "type": "integer"
                },
                "proj_info": {
                    "type": "string"
                },
                "proj_name": {
                    "type": "string"
                },
                "status": {
                    "description": "1 正常、2 回收站",
                    "type": "integer"
                },
                "user_id": {
                    "description": "项目创建者",
                    "type": "integer"
                }
            }
        },
        "database.Prototype": {
            "type": "object",
            "properties": {
                "proj_id": {
                    "type": "integer"
                },
                "prototype_id": {
                    "type": "integer"
                },
                "prototype_name": {
                    "type": "string"
                },
                "prototype_url": {
                    "description": "先留着",
                    "type": "string"
                },
                "status": {
                    "description": "1 正常、2 回收站",
                    "type": "integer"
                }
            }
        },
        "database.Uml": {
            "type": "object",
            "properties": {
                "proj_id": {
                    "type": "integer"
                },
                "status": {
                    "description": "1 正常、2 回收站",
                    "type": "integer"
                },
                "uml_id": {
                    "type": "integer"
                },
                "uml_name": {
                    "type": "string"
                },
                "uml_url": {
                    "type": "string"
                }
            }
        },
        "database.User": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "realName": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                },
                "userInfo": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.AddMemberA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.AddMemberQ": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.CreateDocumentA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.CreateDocumentQ": {
            "type": "object",
            "required": [
                "document_name"
            ],
            "properties": {
                "document_name": {
                    "type": "string"
                },
                "proj_id": {
                    "type": "integer"
                }
            }
        },
        "response.CreateGroupA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "group": {
                    "$ref": "#/definitions/database.Group"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.CreateGroupQ": {
            "type": "object",
            "required": [
                "group_name"
            ],
            "properties": {
                "group_info": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                }
            }
        },
        "response.CreatePPageA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.CreatePPageQ": {
            "type": "object",
            "required": [
                "ppage_name",
                "prototype_id"
            ],
            "properties": {
                "ppage_data": {
                    "type": "string"
                },
                "ppage_name": {
                    "type": "string"
                },
                "prototype_id": {
                    "type": "integer"
                }
            }
        },
        "response.CreateProjA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.CreateProjQ": {
            "type": "object",
            "required": [
                "group_id",
                "proj_name"
            ],
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "proj_info": {
                    "type": "string"
                },
                "proj_name": {
                    "type": "string"
                }
            }
        },
        "response.CreatePrototypeA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.CreatePrototypeQ": {
            "type": "object",
            "required": [
                "prototype_name"
            ],
            "properties": {
                "proj_id": {
                    "type": "integer"
                },
                "prototype_name": {
                    "type": "string"
                }
            }
        },
        "response.CreateUmlA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.CreateUmlQ": {
            "type": "object",
            "required": [
                "uml_name"
            ],
            "properties": {
                "proj_id": {
                    "type": "integer"
                },
                "uml_name": {
                    "type": "string"
                }
            }
        },
        "response.DeletePPageA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.DeletePPageQ": {
            "type": "object",
            "required": [
                "ppage_id"
            ],
            "properties": {
                "ppage_id": {
                    "type": "integer"
                }
            }
        },
        "response.DeleteProjA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.DeleteProjQ": {
            "type": "object",
            "required": [
                "proj_id"
            ],
            "properties": {
                "proj_id": {
                    "type": "integer"
                }
            }
        },
        "response.EnterDocumentA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "document": {
                    "$ref": "#/definitions/database.Document"
                },
                "message": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.EnterDocumentQ": {
            "type": "object",
            "required": [
                "document_id"
            ],
            "properties": {
                "document_id": {
                    "type": "integer"
                }
            }
        },
        "response.GetFilesByNameA": {
            "type": "object",
            "properties": {
                "count_documents": {
                    "type": "integer"
                },
                "count_prototypes": {
                    "type": "integer"
                },
                "count_umls": {
                    "type": "integer"
                },
                "documents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Document"
                    }
                },
                "message": {
                    "type": "string"
                },
                "prototypes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Prototype"
                    }
                },
                "success": {
                    "type": "boolean"
                },
                "umls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Uml"
                    }
                }
            }
        },
        "response.GetFilesByNameQ": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "response.GetGroupsA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Group"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetIdentityA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetIdentityQ": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer"
                }
            }
        },
        "response.GetMembersA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.GroupMember"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetMembersQ": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer"
                }
            }
        },
        "response.GetPPageByIDA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "ppage": {
                    "$ref": "#/definitions/database.PPage"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetPPageByIDQ": {
            "type": "object",
            "required": [
                "ppage_id"
            ],
            "properties": {
                "ppage_id": {
                    "type": "integer"
                }
            }
        },
        "response.GetPPagesA": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "ppages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.PPageID"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetPPagesQ": {
            "type": "object",
            "required": [
                "prototype_id"
            ],
            "properties": {
                "prototype_id": {
                    "type": "integer"
                }
            }
        },
        "response.GetProjAllA": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "projs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Proj"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetProjAllQ": {
            "type": "object"
        },
        "response.GetProjByIDA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "proj": {
                    "$ref": "#/definitions/database.Proj"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetProjByIDQ": {
            "type": "object",
            "required": [
                "proj_id"
            ],
            "properties": {
                "proj_id": {
                    "type": "integer"
                }
            }
        },
        "response.GetProjByNameA": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "projs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Proj"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetProjByNameQ": {
            "type": "object",
            "properties": {
                "proj_name": {
                    "type": "string"
                }
            }
        },
        "response.GetProjCreateA": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "projs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Proj"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetProjCreateQ": {
            "type": "object"
        },
        "response.GetProjDocumentsA": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "documents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Document"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetProjDocumentsQ": {
            "type": "object",
            "required": [
                "proj_id"
            ],
            "properties": {
                "proj_id": {
                    "type": "integer"
                }
            }
        },
        "response.GetProjJoinA": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "projs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Proj"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetProjJoinQ": {
            "type": "object"
        },
        "response.GetProjPrototypesA": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "prototypes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Prototype"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.GetProjPrototypesQ": {
            "type": "object",
            "required": [
                "proj_id"
            ],
            "properties": {
                "proj_id": {
                    "type": "integer"
                }
            }
        },
        "response.GetProjUmlsA": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "umls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Uml"
                    }
                }
            }
        },
        "response.GetProjUmlsQ": {
            "type": "object",
            "required": [
                "proj_id"
            ],
            "properties": {
                "proj_id": {
                    "type": "integer"
                }
            }
        },
        "response.GetUserInfoA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "poster": {
                    "$ref": "#/definitions/database.User"
                },
                "success": {
                    "type": "boolean"
                },
                "user": {
                    "$ref": "#/definitions/database.User"
                }
            }
        },
        "response.GetUserInfoQ": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "response.LoginA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/database.User"
                }
            }
        },
        "response.LoginQ": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.ModifyGroupA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "group": {
                    "$ref": "#/definitions/database.Group"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.ModifyGroupQ": {
            "type": "object",
            "required": [
                "group_id"
            ],
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "group_info": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                }
            }
        },
        "response.ModifyInfoA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.ModifyInfoQ": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.ModifyPasswordA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.ModifyPasswordQ": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "response.MoveDocumentToBinA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.MoveDocumentToBinQ": {
            "type": "object",
            "required": [
                "document_id"
            ],
            "properties": {
                "document_id": {
                    "type": "integer"
                }
            }
        },
        "response.MoveProjBinA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.MoveProjBinQ": {
            "type": "object",
            "required": [
                "proj_id"
            ],
            "properties": {
                "proj_id": {
                    "type": "integer"
                }
            }
        },
        "response.MovePrototypeToBinA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.MovePrototypeToBinQ": {
            "type": "object",
            "required": [
                "prototype_id"
            ],
            "properties": {
                "prototype_id": {
                    "type": "integer"
                }
            }
        },
        "response.MoveUmlToBinA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.MoveUmlToBinQ": {
            "type": "object",
            "required": [
                "uml_id"
            ],
            "properties": {
                "uml_id": {
                    "type": "integer"
                }
            }
        },
        "response.QuitDocumentA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "document": {
                    "$ref": "#/definitions/database.Document"
                },
                "message": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.QuitDocumentQ": {
            "type": "object",
            "required": [
                "document_id"
            ],
            "properties": {
                "document_id": {
                    "type": "integer"
                }
            }
        },
        "response.RegisterA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.RegisterQ": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.RemoveMemberA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.RemoveMemberQ": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "response.SetMemberStatusA": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.SetMemberStatusQ": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "response.UpdateDocumentA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.UpdateDocumentQ": {
            "type": "object",
            "required": [
                "document_id",
                "document_name"
            ],
            "properties": {
                "document_id": {
                    "type": "integer"
                },
                "document_name": {
                    "type": "string"
                }
            }
        },
        "response.UpdatePPageA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.UpdatePPageQ": {
            "type": "object",
            "required": [
                "ppage_id"
            ],
            "properties": {
                "ppage_data": {
                    "type": "string"
                },
                "ppage_id": {
                    "type": "integer"
                },
                "ppage_name": {
                    "type": "string"
                }
            }
        },
        "response.UpdateProjA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.UpdateProjQ": {
            "type": "object",
            "required": [
                "proj_id",
                "proj_name"
            ],
            "properties": {
                "proj_id": {
                    "type": "integer"
                },
                "proj_info": {
                    "type": "string"
                },
                "proj_name": {
                    "type": "string"
                }
            }
        },
        "response.UpdatePrototypeA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.UpdatePrototypeQ": {
            "type": "object",
            "required": [
                "prototype_id",
                "prototype_name"
            ],
            "properties": {
                "prototype_id": {
                    "type": "integer"
                },
                "prototype_name": {
                    "type": "string"
                }
            }
        },
        "response.UpdateUmlA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.UpdateUmlQ": {
            "type": "object",
            "required": [
                "uml_id",
                "uml_name"
            ],
            "properties": {
                "uml_id": {
                    "type": "integer"
                },
                "uml_name": {
                    "type": "string"
                }
            }
        },
        "response.UploadDocumentA": {
            "type": "object",
            "properties": {
                "Rank": {
                    "type": "integer"
                },
                "code": {
                    "type": "integer"
                },
                "document": {
                    "$ref": "#/definitions/database.Document"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
