definitions:
  model.GroupMember:
    properties:
      email:
        type: string
      realName:
        type: string
      status:
        type: string
      userID:
        type: integer
      username:
        type: string
    type: object
  model.Proj:
    properties:
      group_id:
        description: 项目所属团队
        type: integer
      proj_id:
        type: integer
      proj_info:
        type: string
      proj_name:
        type: string
      status:
        description: 1 正常、2 回收站
        type: integer
      user_id:
        description: 项目创建者
        type: integer
    type: object
  model.User:
    properties:
      age:
        type: integer
      email:
        type: string
      password:
        type: string
      realName:
        type: string
      sex:
        type: string
      userID:
        type: integer
      userInfo:
        type: string
      username:
        type: string
    type: object
  response.AddMemberA:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  response.AddMemberQ:
    properties:
      group_id:
        type: integer
      user_id:
        type: integer
    type: object
  response.CreateProjA:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  response.CreateProjQ:
    properties:
      group_id:
        type: integer
      proj_info:
        type: string
      proj_name:
        type: string
    type: object
  response.DeleteProjA:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  response.DeleteProjQ:
    properties:
      proj_id:
        type: integer
    type: object
  response.GetIdentityA:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
  response.GetIdentityQ:
    properties:
      group_id:
        type: integer
    type: object
  response.GetMembersA:
    properties:
      code:
        type: integer
      members:
        items:
          $ref: '#/definitions/model.GroupMember'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  response.GetMembersQ:
    properties:
      group_id:
        type: integer
    type: object
  response.GetProjAllA:
    properties:
      count:
        type: integer
      message:
        type: string
      projs:
        items:
          $ref: '#/definitions/model.Proj'
        type: array
      success:
        type: boolean
    type: object
  response.GetProjAllQ:
    type: object
  response.GetProjByNameA:
    properties:
      count:
        type: integer
      message:
        type: string
      projs:
        items:
          $ref: '#/definitions/model.Proj'
        type: array
      success:
        type: boolean
    type: object
  response.GetProjByNameQ:
    properties:
      proj_name:
        type: string
    type: object
  response.GetProjCreateA:
    properties:
      count:
        type: integer
      message:
        type: string
      projs:
        items:
          $ref: '#/definitions/model.Proj'
        type: array
      success:
        type: boolean
    type: object
  response.GetProjCreateQ:
    type: object
  response.GetProjJoinA:
    properties:
      count:
        type: integer
      message:
        type: string
      projs:
        items:
          $ref: '#/definitions/model.Proj'
        type: array
      success:
        type: boolean
    type: object
  response.GetProjJoinQ:
    type: object
  response.GetUserInfoA:
    properties:
      code:
        type: integer
      message:
        type: string
      poster:
        $ref: '#/definitions/model.User'
      success:
        type: boolean
      user:
        $ref: '#/definitions/model.User'
    type: object
  response.GetUserInfoQ:
    properties:
      user_id:
        type: integer
    type: object
  response.LoginA:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
      token:
        type: string
    type: object
  response.LoginQ:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  response.MoveProjBinA:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  response.MoveProjBinQ:
    properties:
      proj_id:
        type: integer
    type: object
  response.RegisterA:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  response.RegisterQ:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  response.RemoveMemberA:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  response.RemoveMemberQ:
    properties:
      group_id:
        type: integer
      user_id:
        type: integer
    type: object
  response.SetMemberStatusA:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  response.SetMemberStatusQ:
    properties:
      group_id:
        type: integer
      status:
        type: integer
      user_id:
        type: integer
    type: object
  response.UpdateProjA:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  response.UpdateProjQ:
    properties:
      proj_id:
        type: integer
      proj_info:
        type: string
      proj_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /create_proj:
    post:
      consumes:
      - application/json
      parameters:
      - description: 项目名称，项目详情（可选），所属团队ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.CreateProjQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CreateProjA'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.CreateProjA'
      summary: 创建项目
      tags:
      - Proj1
  /delete_proj:
    post:
      consumes:
      - application/json
      parameters:
      - description: 项目ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.DeleteProjQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.DeleteProjA'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.DeleteProjA'
      summary: 删除项目
      tags:
      - Proj1
  /get_proj_all:
    post:
      consumes:
      - application/json
      parameters:
      - description: 无
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.GetProjAllQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetProjAllA'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.GetProjAllA'
      summary: 全部项目
      tags:
      - Proj1
  /get_proj_by_name:
    post:
      consumes:
      - application/json
      parameters:
      - description: 项目名称（不一定是全名，子串搜索）
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.GetProjByNameQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetProjByNameA'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.GetProjByNameA'
      summary: 搜索框
      tags:
      - Proj1
  /get_proj_create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 无
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.GetProjCreateQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetProjCreateA'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.GetProjCreateA'
      summary: 我创建的
      tags:
      - Proj1
  /get_proj_join:
    post:
      consumes:
      - application/json
      parameters:
      - description: 无
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.GetProjJoinQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetProjJoinA'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.GetProjJoinA'
      summary: 我参与的
      tags:
      - Proj1
  /group/add_member:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户id，团队id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.AddMemberQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.AddMemberA'
      tags:
      - Group
  /group/get_group_members:
    post:
      consumes:
      - application/json
      parameters:
      - description: 团队id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.GetMembersQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetMembersA'
      tags:
      - Group
  /group/get_identity:
    post:
      consumes:
      - application/json
      parameters:
      - description: 团队id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.GetIdentityQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetIdentityA'
      tags:
      - Group
  /group/remove_member:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户id，团队id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.RemoveMemberQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RemoveMemberA'
      tags:
      - Group
  /group/set_member_status:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户id，团队id，状态
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.SetMemberStatusQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SetMemberStatusA'
      tags:
      - Group
  /info:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.GetUserInfoQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetUserInfoA'
      tags:
      - User
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.LoginQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginA'
      tags:
      - User
  /move_proj_to_bin:
    post:
      consumes:
      - application/json
      parameters:
      - description: 项目ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.MoveProjBinQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.MoveProjBinA'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.MoveProjBinA'
      summary: 移入或移出回收站
      tags:
      - Proj1
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.RegisterQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RegisterA'
      tags:
      - User
  /update_proj:
    post:
      consumes:
      - application/json
      parameters:
      - description: 项目ID，项目名称（必填，可以填原名，不能和其他项目同名），项目详情（可选）
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.UpdateProjQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UpdateProjA'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.UpdateProjA'
      summary: 修改项目名称、项目描述
      tags:
      - Proj1
swagger: "2.0"
