definitions:
  model.User:
    properties:
      age:
        type: integer
      email:
        type: string
      password:
        type: string
      realName:
        type: string
      sex:
        type: string
      userID:
        type: integer
      userInfo:
        type: string
      username:
        type: string
    type: object
  response.GetUserInfoA:
    properties:
      code:
        type: integer
      message:
        type: string
      poster:
        $ref: '#/definitions/model.User'
      success:
        type: boolean
      user:
        $ref: '#/definitions/model.User'
    type: object
  response.GetUserInfoQ:
    properties:
      user_id:
        type: integer
    type: object
  response.LoginA:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
      token:
        type: string
    type: object
  response.LoginQ:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  response.RegisterA:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  response.RegisterQ:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  response.RemoveMemberA:
    properties:
      code:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  response.RemoveMemberQ:
    properties:
      group_id:
        type: integer
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /group/remove_member:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户id，团队id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.RemoveMemberQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RemoveMemberA'
      tags:
      - Group
  /info:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.GetUserInfoQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetUserInfoA'
      tags:
      - User
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.LoginQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginA'
      tags:
      - User
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.RegisterQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RegisterA'
      tags:
      - User
swagger: "2.0"
